[manifest]
version = '1.0.0'
priority = 0

# Game#start_run
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
if self.GAME.stake >= 7 then self.GAME.modifiers.enable_perishables_in_shop = true end
if self.GAME.stake >= 8 then self.GAME.modifiers.enable_rentals_in_shop = true end
'''
position = 'at'
payload = ''
match_indent = true

# Game#start_run
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
self.GAME.selected_back:apply_to_run()
'''
position = 'after'
payload = '''
-- orange stake
if self.GAME.stake >= 7 then
    self.GAME.modifiers.booster_ante_scaling = true
end
-- gold stake
if self.GAME.stake >= 8 then
    self.GAME.starting_params.hand_size = self.GAME.starting_params.hand_size - 1
end
'''
match_indent = true
